### PR TITLE
windows support

### PR DESCRIPTION
**Pull request by LinusU**
This bundles binaries for windows, both 32-bit and 64-bit, and updated the code to use them as well.

I haven't tested this because I don't currently have access to a windows machine :sob: 

If anyone can help me with that it would be much appreciated :raised_hands:

You can install this branch like this :tada: 

```bash
npm install LinusU/ssh-keygen#windows-support
```

### CODE REVIEW

**Comment by ericvicenti** [comment]
Thanks for the PR! I'll merge this when we get some confirmation that it works

**Comment by LinusU** [comment]
Pushed a new version that should fix the path, it was `src/bin/___.exe` instead of `bin/___.exe`.

**Comment by LinusU** [comment]
@ericvicenti any updates on this?

**Comment by ericvicenti** [comment]
Thanks for this, sorry for the delay on merging!

Just released 0.3.0 with windows support!

**Comment by LinusU** [comment]
Great, no problem 🎉

**Pull request merged**
